services:
  app:
    image: ghcr.io/esaounkine/uop-thesis:latest
    env_file:
      - path: .env
        required: false
    environment:
      PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./db-data:/app/db-data
    restart: unless-stopped
